import type { InsertAction } from './flow-graph';

// 普通画布、嵌套分支及流程总览共用说明，新增操作时必须补齐。
export const actionDescriptions: Record<InsertAction, string> = {
  imageCheck: '使用 OpenCV 在本地判断指定区域，不调用 AI。适合固定图标、图片勾选状态、黑屏、颜色及多帧变化；不适合业务语义或任意文字识别，不能仅凭外观证明按钮可用或视频卡死。原生属性可读取时优先使用属性判断，证据不足报告无法判定。',
  tap: '记录点击当前选中的组件，回放时重新定位后点击。',
  input: '向当前选中的输入组件写入指定文字，支持 {{变量名}} 引用。',
  extractVariable: '读取组件文字或属性，保存到当前脚本变量供后续节点引用。',
  clearInput: '清空当前选中输入组件的内容。',
  coordinateTap: '点击设备屏幕上的指定 X、Y 坐标。节点中可修改坐标，页面位置变化后需重新确认。',
  longPress: '长按指定元素或屏幕坐标，可设置按住时长，默认按元素定位。',
  keyBack: '执行 Android 系统返回操作。',
  keyHome: '按 Home 键返回设备桌面，不等同于关闭应用。',
  keyRecent: '打开 Android 最近任务列表。',
  keyPower: '发送电源键操作，实际锁屏或唤醒行为由设备当前状态决定。',
  swipe: '按指定起点、终点和时长滑动屏幕。',
  pinch: '执行双指放大或缩小手势，需要当前页面支持缩放。',
  launchApp: '启动指定应用，可放在流程中途或分支中执行。',
  stopApp: '停止当前所选包名的 APP 进程，不删除应用或清除数据；可在节点配置中修改目标包名。',
  openGallery: '打开设备相册应用，不自动选择照片或视频。',
  endFlow: '立即结束当前回放流程，后续节点不再执行。',
  loop: '重复执行循环体，支持固定次数或条件退出，必须设置最大次数。',
  breakLoop: '退出指定的当前或外层循环，继续执行该循环的结束路径。',
  clearAppData: '清除目标应用数据并重置应用状态，可能删除登录信息和本地设置，仅允许在流程开始处添加。',
  popupCondition: '判断目标组件是否存在，可进一步配置指定文本及精确或模糊匹配，按结果进入是或否分支。',
  checkboxState: '读取原生 Checkbox 的 checked 状态，按 true/false 分支执行。',
  radioButtonState: '读取原生 RadioButton 的 checked 状态，按 true/false 分支执行。',
  checkedState: '读取 Checkbox、RadioButton 或 Switch 的真实勾选状态，按 true/false 分支执行。不支持仅用图片表示状态的普通 ImageView。',
  aiRecognition: '将设备截图发送给视觉模型，支持单帧识别、观察结束后统一分析及检测命中后提前结束。默认顺序执行，启用分支后按判断结果选择分支。需要配置支持图片输入的模型；边观察边检测可能多次调用模型，实际响应受模型速度影响。',
  textClick: '在组件树中按指定文字精确或模糊匹配并点击，进入匹配到文字或未匹配到文字分支。不识别图片或自绘画面中的文字。',
  tapIfExists: '找到目标组件时点击，未找到则跳过并继续后续流程。',
  inputIfExists: '找到目标输入组件时写入文字，未找到则跳过。支持 {{变量名}} 引用。',
  clearIfExists: '找到目标输入组件时清空内容，未找到则跳过。',
  backIfExists: '目标组件出现时执行系统返回，未出现则跳过。',
  waitFor: '等待目标组件出现，超过配置的等待时间仍未出现则失败。',
  assertExists: '校验目标组件是否存在，不满足时记录执行失败。旧脚本兼容操作。',
  assertText: '校验组件文字是否满足预期，不满足时记录执行失败。旧脚本兼容操作。',
  waitDisappear: '等待目标组件消失，超时仍存在则失败。',
  waitActivity: '等待设备切换到指定的 Activity，适合确认页面跳转是否完成。',
  delay: '暂停指定的毫秒数后继续执行，不判断页面是否已经准备完成。',
  runScript: '执行连接的子脚本，支持显式传入参数并将返回变量映射到当前脚本。',
  noop: '不执行设备操作，作为流程占位节点。',
  log: '输出自定义内容和日志关键字，默认前缀为 stageLog，支持 {{变量名}} 引用。',
  visualChangeStart: '截取指定组件或区域作为基准，与对应结束节点的截图比较。未添加对应结束节点时不比较。',
  visualChangeEnd: '与同一可达路径上对应的开始截图比较，报告变化结果；多组检测可选择对应的开始节点。',
  visualChange: '比较指定区域的截图变化，不直接判断业务状态或图片单选框是否勾选。',
};
